### ISSUE TITLE
Why isn't UTF7_F_USED cleared in utf7_close() ?

### ISSUE THREAD

**Issue by Robinson-George** [skeeto/utf-7#3]
What is the utility of UTF7_F_USED remaining set after UTF7_F_OPEN has been cleared ?

```
utf7_close(UTF7CONTEXT *ctx, int next)
{
    if (ctx->flags & UTF7_F_OPEN) {
        /* An encoding is currently open */
        if (!ctx->len)
            return UTF7_FULL;

        /* Flush remaining bits */
        if (ctx->bits) {
            int a = (ctx->accum << (6 - ctx->bits)) & 0x3fUL;
            *ctx->buf++ = utf7_base64e(a);
            ctx->len--;
            ctx->bits = 0;
        }

        /* Close the encoding */
        if (next == 0x2d || utf7_base64d(next) != -1)  //if '-' or one of the Base64 chars
		{
            if (!ctx->len)
                return UTF7_FULL;
            *ctx->buf++ = 0x2d; /* '-' */
            ctx->len--;
        }
        ctx->flags &= ~UTF7_F_OPEN;  //Why isn't UTF7_F_USED cleared here, too ?
    }
    return UTF7_OK;
```

**Comment by skeeto** [comment]
When UTF7_F_OPEN is unset, the state of UTF7_F_USED is irrelevant. It 
only matters when an indirect encoding is open. So instead of clearing 
UTF7_F_USED upon closing an indirect encoding, it's cleared when 
opening, which is when it matters again. The code is just literally 
encoding that logic.

There's not any particular reason to avoid clearing it when closing and 
prefer clearing it later at the last moment. Both are equally correct. 
It would probably be more efficient to clear when closing since it can 
be done for "free" while already clearing the UTF7_F_OPEN flag. The 
flags are going in the opposite direction when opening an indirect 
encoding.

**Comment by Robinson-George** [comment]
I understand.  If UTF7_F_USED was cleared in utf7_close() then I could compress the lookup table mentioned in the other issue even further.
